name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: get-diff
        run: |
          git fetch origin main
          git diff --name-only HEAD~1 HEAD > changed.txt
          echo "Changed files:"
          cat changed.txt

      - name: Detect changed services
        id: detect
        run: |
          export CHANGED_FILES="$(cat changed.txt)"
          python3 detect_changed_services.py > services.txt
          echo "SERVICES=$(cat services.txt)" >> $GITHUB_ENV

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          echo "Services to deploy: $SERVICES"
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<'ENDSSH'
          cd ${{ secrets.DEPLOY_DIR }}
          git pull
          if echo '$SERVICES' | grep -q 'all'; then
            docker-compose up --build -d
          else
            for service in $SERVICES; do
              docker-compose build \$service &&
              docker-compose up -d \$service
            done
          fi
          ENDSSH